name: Go
on: [push]

env:
  GODEBUG: tracebackancestors=1000

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - uses: actions/checkout@v2

    - run: |
        go run github.com/ysmood/golangci-lint@latest
        go test -race -coverprofile=coverage.out
        go run github.com/ysmood/got/cmd/check-cov@latest

  other-platforms:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - uses: actions/checkout@v2

    - run: go test -race